Repository litmuschaos/litmus-go, pull requests merged in 2021-08, with the labels that each got.

#424 Auxiliary Application Check for node-memory-hog Experiment and Multiple Target Node Functionality Fix for three Node-Level Experiments
  experiments/generic/node-memory-hog/experiment/node-memory-hog.go
  pkg/utils/common/nodes.go
Labels: Ready For Review

#421 feat(helper-status): fix helper status timeout when helper pod failed
  pkg/result/chaosresult.go
  pkg/status/application.go
Labels: Testing-Done, Ready For Review

#422 feat(pre-chaos): creating prechaos and postchaos event for the neg cases
  chaoslib/litmus/docker-service-kill/lib/docker-service-kill.go
  chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
  chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
  chaoslib/litmus/node-drain/lib/node-drain.go
  chaoslib/litmus/node-io-stress/lib/node-io-stress.go
  chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
  chaoslib/litmus/node-restart/lib/node-restart.go
  chaoslib/litmus/node-taint/lib/node-taint.go
  contribute/developer-guide/templates/experiment.tmpl
  experiments/cassandra/pod-delete/experiment/pod-delete.go
  experiments/generic/container-kill/experiment/container-kill.go
  experiments/generic/disk-fill/experiment/disk-fill.go
  experiments/generic/docker-service-kill/experiment/docker-service-kill.go
  experiments/generic/kubelet-service-kill/experiment/kubelet-service-kill.go
  experiments/generic/node-cpu-hog/experiment/node-cpu-hog.go
  experiments/generic/node-drain/experiment/node-drain.go
  experiments/generic/node-io-stress/experiment/node-io-stress.go
  experiments/generic/node-memory-hog/experiment/node-memory-hog.go
  experiments/generic/node-restart/experiment/node-restart.go
  experiments/generic/node-taint/experiment/node-taint.go
  experiments/generic/pod-autoscaler/experiment/pod-autoscaler.go
  experiments/generic/pod-cpu-hog-exec/experiment/pod-cpu-hog-exec.go
  experiments/generic/pod-cpu-hog/experiment/pod-cpu-hog.go
  experiments/generic/pod-delete/experiment/pod-delete.go
  experiments/generic/pod-dns-error/experiment/pod-dns-error.go
  experiments/generic/pod-dns-spoof/experiment/pod-dns-spoof.go
  experiments/generic/pod-fio-stress/experiment/pod-fio-stress.go
  experiments/generic/pod-io-stress/experiment/pod-io-stress.go
  experiments/generic/pod-memory-hog-exec/experiment/pod-memory-hog-exec.go
  experiments/generic/pod-memory-hog/experiment/pod-memory-hog.go
  experiments/generic/pod-network-corruption/experiment/pod-network-corruption.go
  experiments/generic/pod-network-duplication/experiment/pod-network-duplication.go
  experiments/generic/pod-network-latency/experiment/pod-network-latency.go
  experiments/generic/pod-network-loss/experiment/pod-network-loss.go
  experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
Labels: Testing-Done, Ready For Review

#425 feat(exec-chaos): handle the abort signal
  chaoslib/litmus/pod-cpu-hog-exec/lib/pod-cpu-hog-exec.go
  chaoslib/litmus/pod-memory-hog-exec/lib/pod-memory-hog-exec.go
Labels: Testing-Done, Ready For Review

#434 feat(experiment): derive parent name in pod-delete only
  chaoslib/litmus/kafka-broker-pod-failure/lib/pod-delete.go
  chaoslib/litmus/pod-delete/lib/pod-delete.go
  pkg/cassandra/pod-delete/environment/environment.go
  pkg/generic/container-kill/environment/environment.go
  pkg/generic/disk-fill/environment/environment.go
  pkg/generic/network-chaos/environment/environment.go
  pkg/generic/pod-cpu-hog-exec/environment/environment.go
  pkg/generic/pod-delete/environment/environment.go
  pkg/generic/pod-dns-chaos/environment/environment.go
  pkg/generic/pod-memory-hog-exec/environment/environment.go
  pkg/generic/stress-chaos/environment/environment.go
  pkg/kafka/environment/environment.go
  pkg/utils/common/pods.go
Labels: Testing-Done

#436 (docs): adding host-network for the cmdProbe
  go.mod
  go.sum
  pkg/probe/cmdprobe.go
Labels: Testing-Done

#386 feat(network-partition): Adding pod-network-partition experiment
  bin/experiment/experiment.go
  chaoslib/litmus/pod-network-partition/lib/network-policy.go
  chaoslib/litmus/pod-network-partition/lib/pod-network-partition.go
  experiments/generic/pod-network-partition/README.md
  experiments/generic/pod-network-partition/experiment/pod-network-partition.go
  experiments/generic/pod-network-partition/rbac.yaml
  experiments/generic/pod-network-partition/test/test.yml
  go.sum
  pkg/generic/pod-network-partition/environment/environment.go
  pkg/generic/pod-network-partition/types/types.go
Labels: Testing-Done, Ready For Review

#406 Functionality Updation for GCP VM Instance Stop Experiment in case of Auto-Scaling Group
  chaoslib/litmus/gcp-vm-instance-stop/lib/gcp-vm-instance-stop.go
  experiments/gcp/gcp-vm-instance-stop/experiment/gcp-vm-instance-stop.go
  go.sum
  pkg/cloud/gcp/vm-instance-status.go
  pkg/cloud/gcp/vm-operations.go
Labels: Ready For Review
