Repository litmuschaos/litmus-go, pull requests merged in 2021-05, with the labels that each got.

#355 chore(helper): updating the helper pod status check
  chaoslib/litmus/container-kill/lib/container-kill.go
  chaoslib/litmus/disk-fill/lib/disk-fill.go
  chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
  chaoslib/litmus/network-chaos/lib/network-chaos.go
  chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
  chaoslib/litmus/node-io-stress/lib/node-io-stress.go
  chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
  chaoslib/litmus/node-restart/lib/node-restart.go
  chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
  chaoslib/pumba/container-kill/lib/container-kill.go
  chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
  chaoslib/pumba/memory-chaos/lib/memory-chaos.go
  chaoslib/pumba/network-chaos/lib/network-chaos.go
  chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
  pkg/status/application.go
Labels: Testing-Done

#350 Chore(EC2-checks): Update the ec2 terminate with tags experiment to target only running instances
  chaoslib/litmus/ec2-terminate-by-id/lib/ec2-terminate-by-id.go
  chaoslib/litmus/ec2-terminate-by-tag/lib/ec2-terminate-by-tag.go
  experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
  pkg/cloud/aws/ec2-operations.go
  pkg/kube-aws/ec2-terminate-by-tag/types/types.go
Labels: Testing-Done

#347 Chore(abort): Add abort chaos support for kube-aws experiments
  chaoslib/litmus/ebs-loss/lib/ebs-loss-by-id/lib/ebs-loss-by-id.go
  chaoslib/litmus/ebs-loss/lib/ebs-loss-by-tag/lib/ebs-loss-by-tag.go
  chaoslib/litmus/ebs-loss/lib/ebs-loss.go
  chaoslib/litmus/ec2-terminate-by-id/lib/ec2-terminate-by-id.go
  chaoslib/litmus/ec2-terminate-by-tag/lib/ec2-terminate-by-tag.go
  experiments/kube-aws/ebs-loss-by-id/experiment/ebs-loss-by-id.go
  experiments/kube-aws/ebs-loss-by-tag/experiment/ebs-loss-by-tag.go
  experiments/kube-aws/ec2-terminate-by-id/experiment/ec2-terminate-by-id.go
  experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
Labels: Testing-Done

#351 refactor(chaoslibs): Refactored generic node experiments
  chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go
  chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go
  chaoslib/litmus/node-drain/lib/node-drain.go
  chaoslib/litmus/node-io-stress/lib/node-io-stress.go
  chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go
  chaoslib/litmus/node-restart/lib/node-restart.go
  chaoslib/litmus/node-taint/lib/node-taint.go
  experiments/generic/kubelet-service-kill/experiment/kubelet-service-kill.go
  experiments/generic/node-cpu-hog/experiment/node-cpu-hog.go
  experiments/generic/node-drain/experiment/node-drain.go
  experiments/generic/node-io-stress/experiment/node-io-stress.go
  experiments/generic/node-memory-hog/experiment/node-memory-hog.go
  experiments/generic/node-restart/experiment/node-restart.go
  experiments/generic/node-taint/experiment/node-taint.go
  pkg/generic/kubelet-service-kill/environment/environment.go
  pkg/generic/node-cpu-hog/environment/environment.go
  pkg/generic/node-drain/environment/environment.go
  pkg/generic/node-io-stress/environment/environment.go
  pkg/generic/node-memory-hog/environment/environment.go
  pkg/generic/node-restart/environment/environment.go
  pkg/generic/node-taint/environment/environment.go
  pkg/utils/common/common.go
Labels: Testing-Done

#352 refactor(chaoslibs): Refactored pumba chaoslibs and utils
  chaoslib/pumba/container-kill/lib/container-kill.go
  chaoslib/pumba/cpu-chaos/lib/cpu-chaos.go
  chaoslib/pumba/memory-chaos/lib/memory-chaos.go
  chaoslib/pumba/network-chaos/lib/corruption/corruption.go
  chaoslib/pumba/network-chaos/lib/duplication/duplication.go
  chaoslib/pumba/network-chaos/lib/latency/latency.go
  chaoslib/pumba/network-chaos/lib/loss/loss.go
  chaoslib/pumba/network-chaos/lib/network-chaos.go
  chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
  pkg/clients/clientset.go
  pkg/probe/cmdprobe.go
  pkg/probe/httpprobe.go
  pkg/probe/k8sprobe.go
  pkg/probe/probe.go
  pkg/probe/promProbe.go
  pkg/result/chaosresult.go
  pkg/utils/annotation/annotation.go
  pkg/utils/common/common.go
Labels: Testing-Done

#353 refactor(chaoslibs): Refactored aws & vmware experiments
  chaoslib/litmus/ebs-loss/lib/ebs-loss-by-tag/lib/ebs-loss-by-tag.go
  chaoslib/litmus/ec2-terminate-by-id/lib/ec2-terminate-by-id.go
  chaoslib/litmus/ec2-terminate-by-tag/lib/ec2-terminate-by-tag.go
  chaoslib/litmus/vm-poweroff/lib/vm-poweroff.go
  experiments/kube-aws/ebs-loss-by-id/experiment/ebs-loss-by-id.go
  experiments/kube-aws/ebs-loss-by-tag/experiment/ebs-loss-by-tag.go
  experiments/kube-aws/ec2-terminate-by-id/experiment/ec2-terminate-by-id.go
  experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
  experiments/vmware/vm-poweroff/experiment/vm-poweroff.go
  pkg/cloud/aws/ebs-operations.go
  pkg/cloud/aws/ec2-instance-status.go
  pkg/cloud/aws/ec2-operations.go
  pkg/cloud/vmware/get-vcenter-cookie.go
  pkg/cloud/vmware/start-vm.go
  pkg/cloud/vmware/stop-vm.go
  pkg/cloud/vmware/vm-status.go
  pkg/kube-aws/ebs-loss/environment/environment.go
  pkg/kube-aws/ec2-terminate-by-id/environment/environment.go
  pkg/kube-aws/ec2-terminate-by-tag/environment/environment.go
  pkg/utils/common/common.go
  pkg/vmware/vm-poweroff/environment/environment.go
Labels: Testing-Done

#363 chore(dns): adding spoofmap env in helper pod
  chaoslib/litmus/pod-dns-chaos/helper/dnschaos.go
Labels: Testing-Done

#367 chore(contribution): Adding contribution guide, issue & PR templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Ready For Review

#365 chore(env): : updating the env setter function for the helper pods
  chaoslib/litmus/container-kill/lib/container-kill.go
  chaoslib/litmus/disk-fill/lib/disk-fill.go
  chaoslib/litmus/network-chaos/lib/network-chaos.go
  chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
  pkg/utils/common/common.go
Labels: Ready For Review, Testing-Done

#371 chore(image): reduce the go-runner image size
  bin/experiment/experiment.go
  bin/helper/helper.go
  build/generate_go_binary
  chaoslib/litmus/container-kill/helper/container-kill.go
  chaoslib/litmus/container-kill/lib/container-kill.go
  chaoslib/litmus/disk-fill/helper/disk-fill.go
  chaoslib/litmus/disk-fill/lib/disk-fill.go
  chaoslib/litmus/network-chaos/helper/netem.go
  chaoslib/litmus/network-chaos/lib/network-chaos.go
  chaoslib/litmus/pod-dns-chaos/helper/dnschaos.go
  chaoslib/litmus/pod-dns-chaos/lib/pod-dns-chaos.go
Labels: Ready For Review, Testing-Done
