Repository litmuschaos/litmus-go, pull requests merged in 2022-06, with the labels that each got.

#523 Fix ChaosResult Verdict Updation in GCP Disk Loss by Label Experiment
  experiments/gcp/gcp-vm-disk-loss-by-label/experiment/gcp-vm-disk-loss-by-label.go
Labels: READY TO MERGE

#521 Add --stress-image for stressArgs for pumba lib
  chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
Labels: READY TO REVIEW

#526 Chore[Fix]: Node uncordon when app status check failed inside lib
  chaoslib/litmus/node-drain/lib/node-drain.go
Labels: bug, READY TO REVIEW

#518 cpu-stress Chaos Experiment
  .github/workflows/build.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  bin/experiment/experiment.go
  chaoslib/litmus/cpu-stress/lib/cpu-stress.go
  experiments/os/cpu-stress/README.md
  experiments/os/cpu-stress/experiment/cpu-stress.go
  experiments/os/cpu-stress/rbac.yaml
  experiments/os/cpu-stress/test/test.yml
  pkg/machine/cpu/cpu-status.go
  pkg/os/cpu-stress/environment/environment.go
  pkg/os/cpu-stress/types/types.go
Labels: enhancement, READY TO REVIEW

#524 Chore[New exp]: HTTP Chaos for K8s
  bin/experiment/experiment.go
  bin/helper/helper.go
  build/Dockerfile
  chaoslib/litmus/http-chaos/helper/http-helper.go
  chaoslib/litmus/http-chaos/lib/http-chaos.go
  chaoslib/litmus/http-chaos/lib/latency/latency.go
  chaoslib/litmus/network-chaos/helper/netem.go
  chaoslib/litmus/pod-dns-chaos/helper/dnschaos.go
  experiments/generic/pod-http-latency/README.md
  experiments/generic/pod-http-latency/experiment/pod-http-latency.go
  experiments/generic/pod-http-latency/rbac.yaml
  experiments/generic/pod-http-latency/test/test.yaml
  pkg/generic/http-chaos/environment/environment.go
  pkg/generic/http-chaos/types/types.go
  pkg/utils/common/pods.go
Labels: enhancement, Testing-Done, READY TO REVIEW

#533 Add missing return to AnnotatedApplicationsStatusCheck
  pkg/status/application.go
Labels: bug
