Repository litmuschaos/litmus-go, pull requests merged in 2022-09, with the labels that each got.

#556 Response Body modification in HTTP Status code experiment
  chaoslib/litmus/http-chaos/helper/http-helper.go
  chaoslib/litmus/http-chaos/lib/modify-body/modify-body.go
  chaoslib/litmus/http-chaos/lib/statuscode/status-code.go
  pkg/generic/http-chaos/environment/environment.go
  pkg/generic/http-chaos/types/types.go
Labels: READY TO REVIEW

#511 Added experiment and lib for spring-boot
  bin/experiment/experiment.go
  chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
  experiments/spring-boot/README.md
  experiments/spring-boot/rbac.yaml
  experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
  experiments/spring-boot/spring-boot-chaos/test/test.yml
  pkg/spring-boot/spring-boot-chaos/environment/environment.go
  pkg/spring-boot/spring-boot-chaos/types/types.go
Labels: enhancement, READY TO REVIEW

#565 Optimized the logic for duplicate IP check
  chaoslib/litmus/network-chaos/helper/netem.go
Labels: enhancement
